 @api = http://localhost:3000

GET {{api}}/


###

GET url HTTP/1.1

###

POST url HTTP/1.1
header name: header value

content
###

DELETE url HTTP/1.1


###
PUT url HTTP/1.1
header name: header value

content